# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - eurocats-unconference

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_58665960131A4259A0CDA5E64DD0399F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_45DFC708FB59410B9EDD85E396F20E21 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BE68576AD88F4301AF6CE20107D66A5A }}

      - name: Set Web App Settings
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp config appsettings set --name eurocats-unconference --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --settings \
              NUXT_SESSION_PASSWORD="${{ secrets.NUXT_SESSION_PASSWORD }}" \
              APP_ENV="production" \
              AUTH_GITHUB="${{ vars.AUTH_GITHUB }}" \
              TOPICS_FILE_PATH="${{ vars.TOPICS_FILE_PATH }}" \
              USERS_FILE_PATH="${{ vars.USERS_FILE_PATH }}" \
              MAX_VOTES_PER_TOPIC="${{ vars.MAX_VOTES_PER_TOPIC }}" \
              TOP_TOPICS_COUNT="${{ vars.TOP_TOPICS_COUNT }}"

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'eurocats-unconference'
          slot-name: 'Production'
          package: .
